apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-ingestion
  template:
    metadata:
      labels:
        app: data-ingestion
    spec:
      containers:
      - name: data-ingestion
        image: athira1402/data_ingestion:latest
        # env belongs to the container!
        env:
        - name: TRAINING_URL
          value: http://model-training-service.default.svc.cluster.local:5001/train
        - name: SERVING_URL
          value: http://model-serving-service.default.svc.cluster.local:5002/predict
        - name: DRIFT_URL
          value: http://drift-detection-service.default.svc.cluster.local:5003/drift
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
        - name: model-storage
          mountPath: /mnt/data
      # volumes is a sibling to containers
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: churn-model-pvc