apiVersion: v1
kind: PersistentVolume
metadata:
  name: churn-model-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /data/churn-model
